[[apps]]
name = "gameoflife_color"
application = "gameoflife_color"
path = "APPS:[gameoflife_color]gameoflife_color.elf"
restart_on_failure = false
stack_size = 16384
run_once = true
#args = ["--boot"]
